import "./globals.css";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { StorageProvider } from "@/context/storage";
import { Toaster } from "@/components/ui/toaster";
// const inter = Inter({ subsets: ["latin"] });
import { Analytics } from "@vercel/analytics/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StorageProvider>
        {/* <body className={inter.className}> */}
        <body>
          <main>{children}</main>
          <Toaster />
          <Analytics />
        </body>
      </StorageProvider>
    </html>
  );
}
