import {
  AlertTriangle,
  LaptopIcon,
  Smartphone,
  User2,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ChevronsUpDown,
  CreditCard,
  File,
  Pencil,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Users2,
  Moon,
  MoreVertical,
  Play,
  Heart,
  Pizza,
  Plus,
  Settings,
  LineChart,
  SunMedium,
  Trash,
  Twitter,
  User,
  RefreshCcw,
  DownloadCloud,
  X,
  Eye,
  EyeOff,
  FolderPlus,
  BarChart3,
  ListFilter,
  Group,
  ShoppingCart,
  LayoutDashboard,
  AlertTriangleIcon,
  TrendingUp,
  LogOut,
  TrendingDown,
  FileBarChart,
  Monitor,
  Database,
  Calendar,
  LayoutGrid,
  DollarSign,
  List,
  Search,
  Store,
  XCircle,
  Tag,
  Wallet,
  ArrowLeftRight,
  Lock,
  Menu,
  type XIcon as LucideIcon,
  RotateCw,
  LucideProps,
  ArrowUpRight,
  MousePointer,
  MousePointerClick,
  Crosshair,
  Copy,
  Triangle,
  Link2,
  RefreshCcwIcon,
  Send,
  XCircleIcon,
  CheckCircle2,
  HelpCircleIcon,
  Pause,
  Share,
  MessageSquare,
  Bookmark,
  Music,
  Folder,
  BarChart3Icon,
  LineChartIcon,
  Volume,
  VolumeX,
  Flame,
  ArrowRightFromLineIcon,
  Info,
  Gem,
  Zap,
  Youtube,
  Instagram,
  Facebook,
  BookOpen,
  Globe,
  ShoppingCartIcon,
  GraduationCap,
  Gauge,
  PartyPopper,
  CircuitBoard,
  GraduationCapIcon,
  Trash2,
  BookX,
  ShoppingBag,
  MonitorSmartphone,
  Star,
  Dot,
  MessageCircle,
  MoreVerticalIcon,
  MousePointerClickIcon,
  PlusCircle,
  MousePointer2,
  LucideMousePointerClick,
  Pointer,
  PlusCircleIcon,
  Circle,
} from "lucide-react";

//   export type XIcon = LucideIcon;

export const Icons = {
  circle: Circle,
  plusCircle: PlusCircleIcon,
  pointerClick: LucideMousePointerClick,
  pointer: Pointer,
  cursor: MousePointer2,
  circleAdd: PlusCircle,
  click: MousePointerClickIcon,
  more: MoreVerticalIcon,
  messageCircle: MessageCircle,
  dot: Dot,
  monitorSmartphone: MonitorSmartphone,
  star: Star,
  shoppingBag: ShoppingBag,
  bookX: BookX,
  trash: Trash2,
  graduationCap: GraduationCapIcon,
  circuitBoard: CircuitBoard,
  celebrate: PartyPopper,
  gauge: Gauge,
  learn: GraduationCap,
  cart: ShoppingCartIcon,
  user: User2,
  globe: Globe,
  book: BookOpen,
  youtube: Youtube,
  instaGram: Instagram,
  facebook: Facebook,
  bolt: Zap,
  gem: Gem,
  info: Info,
  arrowRightFromLine: ArrowRightFromLineIcon,
  flame: Flame,
  barChart: BarChart3Icon,
  pencil: Pencil,
  lineChart: LineChartIcon,
  music: Music,
  bookmark: Bookmark,
  comment: MessageSquare,
  share: Share,
  helpCircle: HelpCircleIcon,
  monitor: Monitor,
  checkCircle: CheckCircle2,
  xCircle: XCircleIcon,
  accounts: Users2,
  ArrowUpRight: ArrowUpRight,
  showPassword: Eye,
  hidePassword: EyeOff,
  addCollection: FolderPlus,
  folder: Folder,
  analytics: BarChart3,
  close: X,
  crosshair: Crosshair,
  spinner: Loader2,
  chart: List,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  copy: Copy,
  mousePointer: MousePointer,
  mousePointerClick: MousePointerClick,
  chevronUp: ChevronUp,
  chevronUpDown: ChevronsUpDown,
  lock: Lock,
  volume: Volume,
  volumeX: VolumeX,
  rotate: RotateCw,
  filter: ListFilter,
  collection: Group,
  calendar: Calendar,
  dashboard: LayoutDashboard,
  database: Database,
  download: DownloadCloud,
  update: RefreshCcwIcon,
  followers: User,
  error: AlertTriangleIcon,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  post: FileText,
  page: File,
  pause: Pause,
  profile: User,
  play: Play,
  send: Send,
  rank: FileBarChart,
  media: Image,
  menu: Menu,
  likes: Heart,
  link: Link2,
  logout: LogOut,
  settings: Settings,
  grid: LayoutGrid,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  money: DollarSign,
  warning: AlertTriangle,
  arrowRight: ArrowRight,
  triangle: Triangle,
  search: Search,
  store: Store,
  help: HelpCircle,
  remove: XCircle,
  pizza: Pizza,
  products: Tag,
  sun: SunMedium,
  swap: ArrowLeftRight,
  moon: Moon,
  refresh: RefreshCcw,
  laptop: Laptop,
  wallet: Wallet,
  twitter: Twitter,
  check: Check,
  smartPhone: Smartphone,
  LaptopIcon: LaptopIcon,
};
